### ISSUE TITLE
Failed to open stream 

### ISSUE THREAD

**Issue by pavanfhw** [Okazanta/okazanta-legacy#41]
Build docker image with version v2.3.18
Using envrionment:
```
- DB_DRIVER=sqlite
- APP_KEY=xxxxx
- APP_LOG=errorlog
- APP_ENV=testing
- APP_DEBUG=false
- DEBUG=true
```
Have the following erros when starting the container:
```

[2023-01-26 18:51:17] testing.ERROR: ErrorException: include(/var/www/html/vendor/composer/../../database/seeds/DatabaseSeeder.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/ClassLoader.php:444
Stack trace:
#0 /var/www/html/vendor/composer/ClassLoader.php(444): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/var/ww...', '/var/www/html/v...', 444, Array)
#1 /var/www/html/vendor/composer/ClassLoader.php(444): include()
#2 /var/www/html/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/v...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('DatabaseSeeder')
#4 [internal function]: spl_autoload_call('DatabaseSeeder')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('DatabaseSeeder')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('DatabaseSeeder', Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('DatabaseSeeder', Array)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(74): Illuminate\Foundation\Application->make('DatabaseSeeder')
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(63): Illuminate\Database\Console\Seeds\SeedCommand->getSeeder()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2297): Illuminate\Database\Console\Seeds\SeedCommand->Illuminate\Database\Console\Seeds\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(64): Illuminate\Database\Eloquent\Model::unguarded(Object(Closure))
#12 [internal function]: Illuminate\Database\Console\Seeds\SeedCommand->fire()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#15 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Seeds\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 {main} {"identification":{"id":"4c63c8d3-71d6-486a-b454-4603a682ef9d"}} 


                                                                                                                                    
  [ErrorException]                                                                                                                  
  include(/var/www/html/vendor/composer/../../database/seeds/DatabaseSeeder.php): failed to open stream: No such file or directory  
                                                                                                                                    

Initializing Cachet container ...
Attempting to connect to database ...

Nothing to migrate.
[2023-01-26 18:51:22] testing.ERROR: ErrorException: include(/var/www/html/vendor/composer/../../database/seeds/DatabaseSeeder.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/ClassLoader.php:444
Stack trace:
#0 /var/www/html/vendor/composer/ClassLoader.php(444): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/var/ww...', '/var/www/html/v...', 444, Array)
#1 /var/www/html/vendor/composer/ClassLoader.php(444): include()
#2 /var/www/html/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/v...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('DatabaseSeeder')
#4 [internal function]: spl_autoload_call('DatabaseSeeder')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('DatabaseSeeder')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('DatabaseSeeder', Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('DatabaseSeeder', Array)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(74): Illuminate\Foundation\Application->make('DatabaseSeeder')
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(63): Illuminate\Database\Console\Seeds\SeedCommand->getSeeder()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2297): Illuminate\Database\Console\Seeds\SeedCommand->Illuminate\Database\Console\Seeds\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(64): Illuminate\Database\Eloquent\Model::unguarded(Object(Closure))
#12 [internal function]: Illuminate\Database\Console\Seeds\SeedCommand->fire()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#15 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Seeds\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 {main} {"identification":{"id":"5ab2183f-2055-49bd-8e37-49cab818bbaf"}} 


                                                                                                                                    
  [ErrorException]                                                                                                                  
  include(/var/www/html/vendor/composer/../../database/seeds/DatabaseSeeder.php): failed to open stream: No such file or directory  
                                                                                                                                    

Initializing Cachet container ...
Attempting to connect to database ...

Nothing to migrate.
```

Not sure how to debbug "No such file" with an image built from the official repository

**Comment by steffjenl** [comment]
Hello,

Your forgot the filename for the SQLite database

DB_DATABASE=database/database.sqlite

And create an directory database in the root with write permissions for the php-fpm or webserver user.
